package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.61

import (
	"Hackathon-Management-System/src/auth"
	"Hackathon-Management-System/src/graph/model"
	"context"
	"fmt"

	"github.com/google/uuid"
)

// UpdateUser is the resolver for the UpdateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, input model.UpdateUserInput) (*model.User, error) {
	user, err := auth.GetUser(ctx, r.AppConfig)
	if err != nil {
		return nil, err
	}
	fmt.Println("User :", user)
	userID, _ := uuid.Parse(user.ID)
	user, err = r.UserService.UpdateUser(ctx, userID, input)
	if err != nil {
		return nil, err
	}
	return user, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
